language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"
 - "pypy"
install:
  - pip install tox-travis
script:
  - tox
sudo: false
addons:
  apt:
    packages:
    - libenchant-dev
git:
  depth: false
deploy:
  provider: pypi
  user: Julian
  password: ...
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    python: "3.7"
